// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as indexRouteImport } from "./routes/index";
import { Route as claimRouteImport } from "./routes/claim";
import { Route as joinRouteImport } from "./routes/join";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const claimRoute = claimRouteImport.update({
  id: "/claim",
  path: "/claim",
  getParentRoute: () => rootRouteImport,
} as any);
const joinRoute = joinRouteImport.update({
  id: "/join",
  path: "/join",
  getParentRoute: () => rootRouteImport,
} as any);
const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/claim": typeof claimRoute;
  "/join": typeof joinRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/claim": typeof claimRoute;
  "/join": typeof joinRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/claim": typeof claimRoute;
  "/join": typeof joinRoute;
  "/repos": typeof reposRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/claim"
    | "/join"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/claim"
    | "/join"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/claim"
    | "/join"
    | "/repos"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  claimRoute: typeof claimRoute;
  joinRoute: typeof joinRoute;
  reposRoute: typeof reposRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/claim": {
      id: "/claim";
      path: "/claim";
      fullPath: "/claim";
      preLoaderRoute: typeof claimRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/join": {
      id: "/join";
      path: "/join";
      fullPath: "/join";
      preLoaderRoute: typeof joinRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  claimRoute: claimRoute,
  joinRoute: joinRoute,
  reposRoute: reposRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
